apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artech-ingress
  namespace: artech
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2 # reescrita simples
spec:
  ingressClassName: nginx
  rules:
    - host: artech.local
      http:
        paths:
          - path: /cms(/|$)(.*)
            pathType: ImplementationSpecific 
            backend:
              service:
                name: artech-cms
                port:
                  number: 80
          - path: /client(/|$)(.*)
            pathType: ImplementationSpecific 
            backend:
              service:
                name: artech-client
                port:
                  number: 80
